name: Manual Rollback

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Manual Rollback Action
      uses: raiyanyahya/rollback@master
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
